-- ═══════════════════════════════════════════════════════════════════════════
-- 🛠️ CENTRUM MES: Fix Staging Columns & RPCs for Staging (testbdkulytcya)
-- ═══════════════════════════════════════════════════════════════════════════

-- 1. system_users: зміна id на bigint (бо історично в системі id користувачів — це числа 13, 88 тощо)
DROP TABLE IF EXISTS public.system_users CASCADE;
CREATE TABLE public.system_users (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  login text UNIQUE NOT NULL,
  password text,
  first_name text,
  last_name text,
  position text,
  department text,
  shift text,
  access_rights jsonb DEFAULT '{}'::jsonb,
  notification_settings jsonb DEFAULT '{}'::jsonb,
  avatar text,
  last_seen text,
  shift_calendar jsonb DEFAULT '[]'::jsonb,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE public.system_users ENABLE ROW LEVEL SECURITY;
CREATE POLICY "staging_all_access_system_users" ON public.system_users FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- 2. nomenclatures_v2: додати колонки code та status
ALTER TABLE public.nomenclatures_v2 ADD COLUMN IF NOT EXISTS code text;
ALTER TABLE public.nomenclatures_v2 ADD COLUMN IF NOT EXISTS status text DEFAULT 'active';

-- 3. bom_items: додати колонки group_label та code
ALTER TABLE public.bom_items ADD COLUMN IF NOT EXISTS group_label text;
ALTER TABLE public.bom_items ADD COLUMN IF NOT EXISTS code text;

-- 4. Допоміжні таблиці системи для усунення запитів на фронтенді
CREATE TABLE IF NOT EXISTS public.system_configs (
  key text PRIMARY KEY,
  value jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);
ALTER TABLE public.system_configs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "staging_all_access_system_configs" ON public.system_configs FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.chat_participants (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  thread_id text,
  user_id text,
  last_read_at timestamptz DEFAULT now()
);
ALTER TABLE public.chat_participants ENABLE ROW LEVEL SECURITY;
CREATE POLICY "staging_all_access_chat_participants" ON public.chat_participants FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- 5. Базова функція touch presence
CREATE OR REPLACE FUNCTION public.rpc_touch_user_presence(p_user_id text DEFAULT NULL, p_status text DEFAULT 'active')
RETURNS void AS $$
BEGIN
  NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 6. RPC verify_user_password (fallback перевірка логіну без Supabase Auth)
CREATE OR REPLACE FUNCTION public.verify_user_password(login_input text, password_input text)
RETURNS jsonb AS $$
DECLARE
  v_user record;
BEGIN
  SELECT * INTO v_user FROM public.system_users WHERE lower(login) = lower(login_input) LIMIT 1;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'Користувача не знайдено');
  END IF;
  IF v_user.password IS NOT NULL AND v_user.password = password_input THEN
    RETURN jsonb_build_object('success', true, 'user', row_to_json(v_user));
  ELSE
    RETURN jsonb_build_object('success', false, 'error', 'Невірний пароль');
  END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
