-- SQL Migration for CRM Leads and Dynamic Pipeline Stages
-- Migration timestamp: 20260828133000

-- 1. Create crm_pipeline_stages table
CREATE TABLE IF NOT EXISTS public.crm_pipeline_stages (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  color TEXT DEFAULT '#6366f1',
  sort_order INT NOT NULL DEFAULT 0,
  is_system BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed initial default stages
INSERT INTO public.crm_pipeline_stages (id, title, color, sort_order, is_system)
VALUES
  ('lead', 'Новий запит (Лід)', '#6366f1', 10, true),
  ('tech_spec', 'Технічна специфікація', '#8b5cf6', 20, true),
  ('quote', 'КП / Рахунок виставлено', '#f59e0b', 30, true),
  ('agreed', 'Підтверджено (Оплата)', '#10b981', 40, true),
  ('in_production', 'Передано в MES', '#ff9000', 50, true)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  color = EXCLUDED.color,
  sort_order = EXCLUDED.sort_order;

-- 2. Create crm_leads table
CREATE TABLE IF NOT EXISTS public.crm_leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  client_name TEXT NOT NULL,
  contact_phone TEXT,
  contact_email TEXT,
  product_interest TEXT,
  quantity INT DEFAULT 1,
  estimated_amount NUMERIC(14,2) DEFAULT 0.00,
  stage_id TEXT REFERENCES public.crm_pipeline_stages(id) ON DELETE SET NULL DEFAULT 'lead',
  notes TEXT,
  manager_name TEXT,
  order_id BIGINT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS and grant permissions
ALTER TABLE public.crm_pipeline_stages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.crm_leads ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public all for crm_pipeline_stages" ON public.crm_pipeline_stages
  FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Allow public all for crm_leads" ON public.crm_leads
  FOR ALL USING (true) WITH CHECK (true);

GRANT ALL ON TABLE public.crm_pipeline_stages TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.crm_leads TO anon, authenticated, service_role;
